baseURL = "https://dotkg.in"
languageCode = "en-us"
title = "KG coder, part-time gamer|rider"
theme = "cactus"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  colortheme = "white" # dark, light, white, or classic
  description = "I create stuffs that empower free learning & OSS. I am also working on a home with sustainable co-operative living."
  mainSection = "Posts"
  tagsOverview = false
  showProjectsList = true

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[params.social]]
  name = "github"
  link = "https://github.com/mrdotkg/"

[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/mrdotkg/"

[[params.social]]
  name = "twitter"
  link = "https://twitter.com/mrdotkg/"

[[params.social]]
  name = "email"
  link = "mr@dotkg.in" # no need for "mailto:" at the start
