baseURL = "https://dotkg.in"
languageCode = "en-us"
title = "KG"
theme = "cactus"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  colortheme = "white" # dark, light, white, or classic
  description = "Coder | Gamer | Rider"
  mainSection = "Posts"
  tagsOverview = false
  showProjectsList = true

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[params.social]]
  name = "github"
  link = "https://github.com/mrdotkg/"

[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/mrdotkg/"

[[params.social]]
  name = "twitter"
  link = "https://twitter.com/mrdotkg/"

# [[params.social]]
#   name = "email"
#   link = "mr@dotkg.in" # no need for "mailto:" at the start
